title: beryx.org
email: admin@beryx.org
baseurl: ""
url: "http://beryx.org"
author: "Serban Iordache"
twitter_username: serban_iordache
github_username:  siordache

intensedebate_id: "9757a7e766f8c73d6914c8a117b4ef7b"

markdown: kramdown
kramdown:
  input: GFM

exclude: ['Gemfile*','README.md']

permalink: "/blog/:year-:month-:day-/:title/"

paginate: 1
paginate_path: "/blog/page:num"
